# Stolen from capitaomorte/yasnippet
language: emacs-lisp

branches:
  except:
    - data

env:
  - EMACS_24_X=1
  - EMACS_24_X=2
  - EMACS_24_X=3
  - EMACS_24_X=4

before_install:
  - make travis-prepare
  - emacs --version
  - cask --version
  - make travis-install

script:
  - make $EMACS_24_X
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/07063bd143e35f54b1e8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
